name       : usermode
version    : '1.113'
release    : 4
source     :
    - https://releases.pagure.org/usermode/usermode-1.113.tar.xz : 99fbfd248b411ed0e7c44d1957b0ecde699b5a968a4db5d37228e82e7b1ba092
license    : GPL-2.0-or-later
component  : programming.devel
summary    : Provide superuser privileges to ordinary users
description: |
    usermode contains the userhelper program, which can be used to allow configured programs to be run with superuser privileges by ordinary users, and several graphical tools for users
# undefined reference to `powl`
clang      : no
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(libuser)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - desktop-file-utils
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    chmod 4711 $installdir/usr/sbin/userhelper
